# Generated by Django 5.2 on 2025-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing_program', models.CharField(choices=[('rdp', 'RDP Housing'), ('social', 'Social Housing'), ('flisp', 'FLISP'), ('rental', 'Rental Housing')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
